application: antipastebin
version: 0-0-1
runtime: go
api_version: go1

handlers:
- url: /fsm
  static_dir: fsm
- url: /txt
  static_dir: txt
- url: /hairs
  static_dir: hairs
- url: /automatons
  static_dir: automatons
- url: /.*
  script: _go_app